### ISSUE TITLE
The Dependency Graph Resolver is processing records at a slow rate

### ISSUE THREAD

**Issue by gdrosos** [fasten-project/data-processing#26]
# Description

Through observing the k8s logs, I noticed that the  Dependency Graph Resolver  is processing the records at a slow rate. Despite having processed all the kafka records, in practise  I noticed that in the past 5 days it has been processing coordinates which have been ingested on May. I would like to ask if we could somehow speed up the analysis. Any help would be really appreciated.

**Comment by mir-am** [comment]
Hi @gdrosos,
Is this issue still relevant?

**Comment by proksch** [comment]
@mir-am Maybe you could check the k8s logs...

The Kafka lag is normal, as the DGR commits manually... what does the log say about progress?

**Comment by mir-am** [comment]
I'd like to close this issue as the DGR is working as expected.
